const mongoose = require('mongoose');

const AnnotationSchema = new mongoose.Schema({
  documentId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Document',
    required: true
  },
  // Custom UUID generated by frontend for easier sync/undo
  id: {
    type: String,
    required: true,
    unique: true
  },
  content: {
    type: Object, // Stores text, image, etc.
    required: true
  },
  position: {
    type: Object, // Stores boundingRect, rects, pageNumber
    required: true
  },
  comment: {
    type: Object, // Stores text, emoji, etc.
    default: null
  },
  type: {
    type: String,
    enum: ['highlight', 'note'],
    default: 'highlight'
  },
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  createdAt: {
    type: Date,
    default: Date.now
  }
});

module.exports = mongoose.model('Annotation', AnnotationSchema);
